---
- name: deploy REPOSITORIES as a Docker container (from the Registry to the SP VM appliance)
  docker_container:
    name: son-catalogue-repos
    image: "sonatanfv/son-catalogue-repos:{{ sp_ver }}"
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-catalogue-repos
    published_ports: "4002:4011"
    restart_policy: "unless-stopped"
